'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowUpRight, ChevronDown, Menu, X } from 'lucide-react'

const faqs = [
  ['What does it actually check?', 'It pulls the requirements out of the posting, then goes through them one at a time against your resume. A match only counts if it can find the line in your text that backs it up. Anything it cannot verify gets marked down rather than counted in your favour.'],
  ['What happens to my resume?', 'The file itself is never saved. The text goes to the model that writes the analysis, and the finished result is held for about an hour so re-running the same pair does not cost a second call. What you see lives in this browser tab and goes when you close it.'],
  ['What can I upload?', 'A PDF, DOCX or plain TXT, up to 4 MB. Export it as text rather than scanning or photographing a printout, because a picture of a resume has no text to read. If a file will not parse, it will say so instead of guessing.'],
  ['Will it rewrite my bullets?', 'It suggests rewrites for a few of them, and it will not put words in your mouth. No number, employer, title or outcome appears that you did not already write. If a bullet has no measurable result, it sharpens the verb instead of inventing a metric. The edit stays yours to make.'],
]

function FAQ() {
  const [open, setOpen] = useState<number | null>(0)
  return <div className="flex flex-col divide-y divide-border border-y border-border">{faqs.map(([q, a], i) => <div key={q}><button aria-expanded={open === i} onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-6 py-6 text-left text-base font-medium transition hover:text-primary"><span>{q}</span><ChevronDown className={`size-5 shrink-0 text-muted-foreground transition-transform ${open === i ? 'rotate-180' : ''}`} /></button><div className={`grid transition-[grid-template-rows] duration-300 ${open === i ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]'}`}><p className="min-h-0 overflow-hidden pr-10 text-sm leading-7 text-muted-foreground">{a}</p></div></div>)}</div>
}

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main className="flex-1 bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b border-border/70 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10"><Link href="/" className="text-lg font-semibold tracking-[-0.05em]">resumefit<span className="text-primary">.</span></Link><nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#features" className="transition hover:text-foreground">Features</a><a href="#how-it-works" className="transition hover:text-foreground">How it works</a><a href="#limits" className="transition hover:text-foreground">Limits</a><a href="#faq" className="transition hover:text-foreground">FAQ</a></nav><div className="hidden items-center md:flex"><a href="mailto:luckyjaiswal3405@gmail.com" className="text-sm text-muted-foreground transition hover:text-foreground">Contact</a></div><button aria-label={menuOpen ? 'Close menu' : 'Open menu'} className="md:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="flex flex-col gap-5 border-t border-border px-5 py-6 text-sm md:hidden"><a href="#features" onClick={() => setMenuOpen(false)}>Features</a><a href="#how-it-works" onClick={() => setMenuOpen(false)}>How it works</a><a href="#limits" onClick={() => setMenuOpen(false)}>Limits</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><a href="mailto:luckyjaiswal3405@gmail.com" onClick={() => setMenuOpen(false)} className="text-muted-foreground">Contact support</a></nav>}</header>
    <section className="relative overflow-hidden border-b border-border"><div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/40 to-transparent"/><div className="mx-auto flex max-w-5xl flex-col items-center px-5 pb-24 pt-20 text-center sm:px-8 sm:pb-32 sm:pt-28 lg:px-10 lg:pb-40 lg:pt-36"><p className="mb-7 text-sm font-medium text-primary">Before you send the application</p><h1 className="max-w-4xl text-balance text-5xl font-semibold leading-[1.03] tracking-[-0.075em] sm:text-7xl lg:text-8xl">Know exactly why you fit.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-muted-foreground sm:text-xl">Paste a job posting and your resume. You get a score, the requirements you genuinely meet, and the line from your own resume that proves each one.</p><div className="mt-10 flex flex-wrap items-center justify-center gap-5"><Link href="/upload" className="group inline-flex items-center rounded-xl bg-primary px-5 py-3.5 text-sm font-semibold text-primary-foreground shadow-[0_12px_30px_-12px_var(--primary)] transition duration-300 hover:brightness-110 hover:shadow-[0_18px_35px_-12px_var(--primary)]">Check my fit <ArrowUpRight className="ml-2 transition-transform duration-300 group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link><a href="#how-it-works" className="text-sm font-medium text-muted-foreground underline underline-offset-4 transition hover:text-foreground">See how it works</a></div><div className="mt-16 grid w-full max-w-2xl grid-cols-3 border-y border-border py-5 text-left sm:mt-20"><div className="pr-4"><p className="text-sm font-semibold">Quoted, not guessed</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Every match shows the line that backs it.</p></div><div className="border-l border-border px-4"><p className="text-sm font-semibold">Nothing invented</p><p className="mt-1 text-xs leading-5 text-muted-foreground">No numbers appear that you did not write.</p></div><div className="border-l border-border pl-4"><p className="text-sm font-semibold">No sign-up</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Results stay in your tab and nowhere else.</p></div></div></div></section>
    <section id="features" className="border-y border-border bg-card"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="max-w-xl"><p className="text-sm font-medium text-primary">Where most resume tools stop</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">The feedback you wish you got before applying.</h2></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-border bg-border md:grid-cols-3">{[['01','It reads the posting first','Requirements come out of the job you pasted, not a generic checklist. Must-haves and nice-to-haves are scored separately, so one missing bonus skill does not sink you.'],['02','It has to show its work','Claiming you match something requires quoting the line that proves it. A skill listed but never demonstrated gets marked down, which is usually the gap worth fixing.'],['03','It will not flatter you','Suggested rewrites keep your facts intact. Nothing is padded, and a weak bullet with no result gets a sharper verb rather than a number someone made up.']].map(([n,t,d]) => <article key={n} className="bg-card p-7 sm:p-9"><span className="font-mono text-xs text-muted-foreground">{n}</span><h3 className="mt-12 text-xl font-semibold tracking-[-0.03em]">{t}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{d}</p></article>)}</div></div></section>
    <section id="how-it-works" className="mx-auto grid max-w-7xl gap-14 px-5 py-24 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-10 lg:py-32"><div><p className="text-sm font-medium text-primary">How it works</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">A clearer application in three steps.</h2></div><div className="flex flex-col divide-y divide-border border-y border-border">{[['Add your resume','The PDF, DOCX or TXT you already send out. Nothing to reformat.'],['Paste the posting','All of it, requirements included. That is what the comparison runs against.'],['Read what came back','A score, what you match, what you do not, and the bullets worth another pass.']].map(([t,d], i) => <div key={t} className="grid gap-4 py-7 sm:grid-cols-[72px_1fr]"><span className="font-mono text-sm text-primary">0{i + 1}</span><div><h3 className="text-lg font-semibold tracking-[-0.02em]">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></div></div>)}</div></section>
    <section id="limits" className="border-y border-border bg-card"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-24 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><div><p className="text-sm font-medium text-primary">Deliberate limits</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">What it will not do.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">A resume tool that agrees with you is not much use. These are the places it is built to push back.</p></div><div className="flex flex-col divide-y divide-border border-y border-border">{[['Count a skill it cannot find','Naming a tool in your skills list is not evidence. To call something a match it has to quote the line in your experience that shows you doing it. When it cannot, the requirement drops into the gaps rather than quietly padding your score.'],['Invent a number to make a bullet land','Rewrites keep your facts. No metric, employer, job title or outcome turns up that you did not write yourself. A bullet with no measurable result gets a stronger verb, not a percentage somebody made up.'],['Score something that is not a resume','Invoices, recipes, contracts and papers are turned away with a reason. Nothing gets run through anyway and handed a number that means nothing.'],['Pretend a model read it when none did','If the written review cannot run, the page says so and falls back to comparing wording. A word match is never dressed up as a considered read.']].map(([t,d]) => <div key={t} className="grid gap-4 py-7 sm:grid-cols-[72px_1fr]"><X className="mt-1 size-4 text-muted-foreground" aria-hidden="true" /><div><h3 className="text-lg font-semibold tracking-[-0.02em]">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></div></div>)}</div></div></section>
    <section id="faq" className="mx-auto grid max-w-7xl gap-12 px-5 py-24 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><div><p className="text-sm font-medium text-primary">Worth knowing first</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.05em]">Before you begin.</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Something not covered here? <a href="mailto:luckyjaiswal3405@gmail.com" className="underline underline-offset-4">Ask me.</a></p></div><FAQ /></section>
  </main>
}
